export enum CharactersActionTypes {
    SET_CHARACTERS_DATA = 'SET_CHARACTERS_DATA',
    SET_CHARACTER_DETAILS = 'SET_CHARACTER_DETAILS',
    CLEAR_CHARACTERS_DATA = 'CLEAR_CHARACTERS_DATA',
}
export enum EpisodesActionTypes {
    SET_EPISODES_DATA = 'SET_EPISODES_DATA',
    SET_EPISODE_DETAILS = 'SET_EPISODE_DETAILS',
    CLEAR_EPISODES_DATA = 'CLEAR_EPISODES_DATA',
}
export enum LocationsActionTypes {
    SET_LOCATIONS_DATA = 'SET_LOCATIONS_DATA',
    SET_LOCATION_DETAILS = 'SET_LOCATION_DETAILS',
    CLEAR_LOCATIONS_DATA = 'CLEAR_LOCATIONS_DATA',
}
